baseURL = "https://sprint.mosqlimate.org/"
languageCode = "en-us"
title = "Mosqlimate - IMDC"
theme = "ananke"
disableKinds = ["RSS", "taxonomy", "term"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blogposts"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "Sprint"
    url = "/sprint/"
    weight = 3

  [[menu.main]]
    name = "Results"
    url = "/results/"
    weight = 4

  [[menu.main]]
    name = "Registration"
    url = "/registration/"
    weight = 5

  [[menu.main]]
    name = "Instructions"
    url = "/instructions/"
    weight = 6

  [[menu.main]]
    name = "Data"
    url = "/data/"
    weight = 7

  [[menu.main]]
    name = "Organizers"
    url = "/organize/"
    weight = 8

  [params]
    custom_css = ["css/custom.css"]
    favicon = ""
    site_logo = "logo-medium.png"

  [markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
